version: "3.9"
services:
  web:
    build: services/frontend
    ports:
      - "5000:5000"
    networks:
      - frontend
      - backend
  reader:
    build: services/reader
    ports:
      - "8080:8080"
    networks:
      - frontend
  writer:
    build: services/writer
    ports:
      - "8081:8081"
    networks:
      - backend
    command: python main.py
  redis:
    image: "redis:alpine"

networks:
  backend:
  frontend: