version: "3.9"
services:
  web:
    build: services/frontend
    ports:
      - "3000:3000"
    networks:
      - default
  reader:
    build: services/reader
    ports:
      - "8080:8080"
    networks:
      - default
    links:
      - redis
  writer:
    build: services/writer
    ports:
      - "8081:8081"
    networks:
      - default
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ./redis:/usr/local/etc/redis
    networks:
      - default

networks:
  default: