name: Continuous deployment

on:
  push:
    branches:
      - master

jobs:
  create-envfile:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_SECRET_KEY: ${{ secrets.SECRET_KEY }}
          directory: challenge-01/frontend
          file_name: .env
          fail_on_empty: false

  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push frontend
        working-directory: challenge-01/frontend
      - uses: docker/build-push-action@v3
        with:
          push: true
          tags: user/app:latest
      -
        name: Build and push backend
        working-directory: challenge-01/backend
      - uses: docker/build-push-action@v3
        with:
          push: true
          tags: user/app:latest