name: Continuous deployment

on:
  push:
    branches:
      - master

jobs:

  create-envfile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_SECRET_KEY: ${{ secrets.SECRET_KEY }}
          directory: challenge-01/frontend
          file_name: .env
          fail_on_empty: false

